// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'tabPanelBoxParagraph': string;
  'tabPanelBoxParagraphLine': string;
  'tabPanelBoxTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
