// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'hash': string;
  'tabListButton': string;
}
export const cssExports: CssExports;
export default cssExports;
